#%RAML 1.0 DataType
type: array
items:
  type: object
  properties:
    phoneNumber:
      type: string
      required: true
      example: "1234567893"
    name:
      type: string
      required: true
      example: "abcd"
    email:
      type: string
      required: true
      example: "asnd@gmail.com"
    customer_ID: 
      type: string
      required: true
      example: "12358"
    mobileNumber:
      type: number
      required: false
      example: 1234567895
    registrationDate:
      type: string
      required: true
      example: "15-01-2000"
    gender:
      type: string
      required: true
      example: "Male"
    status:
      type: string
      required: true
      example: "Single"
    address:
      type: string
      required: true
      example: "Banglore"
    dateOfBirth:
      type: string
      required: true
      example: "23-01-96"
